sudo: false

language: node_js

node_js:
  - "8.9.1"
  - "node"
  - "lts"

before_install:
  - npm list -g

install:
  - npm install
  - npm install -g codecov

script:
  - npm run test --code-coverage --sourcemaps=false --environment=prod --progress
  - codecov
