sudo: required
dist: trusty
language: node_js
node_js:
  - "8.9.1"
  - "node"
  - "lts/*"

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
      - google-chrome-beta

env:


before_install:
  - export CHROME_BIN=/usr/bin/google-chrome
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

install:
  - npm install -g angular-cli codecov
  - npm install

script:
  - ng build --prod
  - npm run test --code-coverage --sourcemaps=false --environment prod --progress
  - codecov
