sudo: required
dist: trusty
language: node_js
node_js:
  - "8.9.1"

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
      - google-chrome-beta

before_install:
  - export CHROME_BIN=/usr/bin/google-chrome
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

install:
  - npm install -g angular-cli codacy-coverage
  - npm install

script:
  - ng lint
  - ng test earthquake-geoserve-ui --code-coverage
  - ng test location-input --code-coverage
  - ng test geoserve-output --code-coverage
  - ng build --prod --base-href /geoserve/
  - ng build --prod location-input
  - ng build --prod geoserve-output
  - ng e2e

after_success:
  - cat coverage/lcov.info | codacy-coverage --verbose
